services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
    - .env
    volumes:
      - ./config:/config
    ports:
      - 444:443
      - 81:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped